/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.HangarToUI;
import deepspace.WeaponToUI;
import deepspace.ShieldToUI;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author ana
 */
public class HangarView extends javax.swing.JPanel {

    /**
     * Creates new form HangarView
     */
    public HangarView() {
        initComponents();
    }
    
    public void setHangar(HangarToUI h){
     // String titulo = "Hangar de " + Integer.toString(h.getMaxElements()) + " espacios";
     // setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), titulo));
        //lEspacio.setText("Espacio de " + Integer.toString(h.getMaxElements()));
     pHangar.removeAll();
        for(ShieldToUI s: h.getShieldBoosters()){
            ShieldBoosterView sw = new ShieldBoosterView();
            sw.setShieldBooster(s);
            pHangar.add(sw);
        }
        
        for(WeaponToUI w: h.getWeapons()){
            WeaponView wv = new WeaponView();
            wv.setWeapon(w);
            pHangar.add(wv);
        }
    }
    
    public ArrayList<Integer> getSelected(){
        ArrayList<Integer> selected = new ArrayList();
        int i = 0;
        for (Component c : pHangar.getComponents()) {
            if (((CombatElementView) c).isSelected()) {
                selected.add(i);
            }
            i++;
        }
        return selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollHangar = new javax.swing.JScrollPane();
        pHangar = new javax.swing.JPanel();

        jScrollHangar.setViewportView(pHangar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollHangar, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollHangar, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollHangar;
    private javax.swing.JPanel pHangar;
    // End of variables declaration//GEN-END:variables
}
